version: "3.8"

services:
  postgres:
    image: postgres:18
    container_name: naxos-backend-challenge-postgres
    environment:
      POSTGRES_DB: naxos-backend-challenge
      POSTGRES_USER: naxos-backend-challenge
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - naxos-backend-challenge-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U naxos-backend-challenge"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - naxos-backend-challenge-net

  redis:
    image: redis:7-alpine
    container_name: naxos-backend-challenge-redis
    ports:
      - "6379:6379"
    volumes:
      - naxos-backend-challenge-redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - naxos-backend-challenge-net

volumes:
  naxos-backend-challenge-data:
  naxos-backend-challenge-redis-data:

networks:
  naxos-backend-challenge-net:
